# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\menu_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu_inicial(object):
    def setupUi(self, menu_inicial):
        menu_inicial.setObjectName("menu_inicial")
        menu_inicial.resize(800, 500)
        menu_inicial.setMinimumSize(QtCore.QSize(800, 500))
        menu_inicial.setMaximumSize(QtCore.QSize(1200, 600))
        menu_inicial.setStyleSheet("QPushButton#acessar, #criar, #graficos, #ajuda{\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 5px\n"
"}\n"
"QPushButton#acessar:hover, #criar:hover, #graficos:hover, #ajuda:hover{\n"
"background-color: rgba(145, 207, 230, 200)\n"
"}\n"
"QPushButton#acessar:pressed, #criar:pressed, #graficos:pressed, #ajuda:pressed{\n"
"background-color: rgba(150, 150, 150, 255);\n"
"padding-top: 2px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(menu_inicial)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acessar = QtWidgets.QPushButton(menu_inicial)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.acessar.setFont(font)
        self.acessar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.acessar.setObjectName("acessar")
        self.horizontalLayout.addWidget(self.acessar)
        self.criar = QtWidgets.QPushButton(menu_inicial)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.criar.setFont(font)
        self.criar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.criar.setObjectName("criar")
        self.horizontalLayout.addWidget(self.criar)
        self.graficos = QtWidgets.QPushButton(menu_inicial)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.graficos.setFont(font)
        self.graficos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graficos.setObjectName("graficos")
        self.horizontalLayout.addWidget(self.graficos)
        self.ajuda = QtWidgets.QPushButton(menu_inicial)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ajuda.setFont(font)
        self.ajuda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ajuda.setObjectName("ajuda")
        self.horizontalLayout.addWidget(self.ajuda)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(menu_inicial)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(menu_inicial)
        self.calendarWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.calendarWidget.setMaximumSize(QtCore.QSize(1000, 500))
        self.calendarWidget.setStyleSheet("selection-background-color: rgb(115, 107, 221);\n"
"")
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(menu_inicial)
        self.label.setMinimumSize(QtCore.QSize(200, 200))
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/imagens/logo png.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.versao = QtWidgets.QPushButton(menu_inicial)
        self.versao.setEnabled(True)
        self.versao.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.versao.setFont(font)
        self.versao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.versao.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.versao.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.versao.setAutoDefault(False)
        self.versao.setDefault(False)
        self.versao.setFlat(False)
        self.versao.setObjectName("versao")
        self.verticalLayout.addWidget(self.versao, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(menu_inicial)
        QtCore.QMetaObject.connectSlotsByName(menu_inicial)

    def retranslateUi(self, menu_inicial):
        _translate = QtCore.QCoreApplication.translate
        menu_inicial.setWindowTitle(_translate("menu_inicial", "Form"))
        self.acessar.setText(_translate("menu_inicial", "A c e s s a r"))
        self.criar.setText(_translate("menu_inicial", "C r i a r"))
        self.graficos.setText(_translate("menu_inicial", "G r á f i c o s"))
        self.ajuda.setText(_translate("menu_inicial", "A j u d a"))
        self.label_2.setText(_translate("menu_inicial", "PreMia"))
        self.versao.setText(_translate("menu_inicial", "V e r s ã o 1.1.0"))
