# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tela_adicionar_dados_glicemia.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        Form.setMinimumSize(QtCore.QSize(600, 400))
        Form.setMaximumSize(QtCore.QSize(600, 500))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setStyleSheet("QPushButton#adicionar_peso, #excluir_peso, #adicionar_glicemia, #excluir_glicemia, #adicionar_banco_dados{\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 5px\n"
"}\n"
"QPushButton#adicionar_peso:hover, #excluir_peso:hover, #adicionar_glicemia:hover, #excluir_glicemia:hover, #adicionar_banco_dados:hover{\n"
"background-color: rgba(145, 207, 230, 200)\n"
"}\n"
"QPushButton#adicionar_peso:pressed, #excluir_peso:pressed, #adicionar_glicemia:pressed, #excluir_glicemia:pressed, #adicionar_banco_dados:pressed{\n"
"background-color: rgba(150, 150, 150, 255);\n"
"padding-top: 2px;\n"
"}\n"
"\n"
"QLineEdit#linha_peso, #linha_glicemia{\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(0, 0, 0)\n"
"}\n"
"QLineEdit#linha_peso:hover, #linha_glicemia:hover{\n"
"background-color: rgba(147, 207, 230, 100)\n"
"}\n"
"\n"
"QComboBox#combo_dia, #combo_mes, #combo_ano{\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 5px\n"
"}\n"
"QComboBox#combo_dia:hover, #combo_mes:hover, #combo_ano:hover{\n"
"background-color: rgba(147, 207, 230, 200)\n"
"}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.ajuda = QtWidgets.QPushButton(Form)
        self.ajuda.setMinimumSize(QtCore.QSize(30, 30))
        self.ajuda.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ajuda.setFont(font)
        self.ajuda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ajuda.setStyleSheet("QPushButton#ajuda{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 10px\n"
"}\n"
"QPushButton#ajuda:hover{\n"
"background-color: rgba(145, 207, 230, 200)\n"
"}\n"
"QPushButton#ajuda:pressed{\n"
"padding-top: 2px\n"
"}\n"
"")
        self.ajuda.setObjectName("ajuda")
        self.horizontalLayout_4.addWidget(self.ajuda)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.combo_dia = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_dia.setFont(font)
        self.combo_dia.setObjectName("combo_dia")
        self.horizontalLayout_7.addWidget(self.combo_dia)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.combo_mes = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_mes.setFont(font)
        self.combo_mes.setObjectName("combo_mes")
        self.horizontalLayout_8.addWidget(self.combo_mes)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.combo_ano = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_ano.setFont(font)
        self.combo_ano.setObjectName("combo_ano")
        self.horizontalLayout_9.addWidget(self.combo_ano)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lista_valores = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lista_valores.setFont(font)
        self.lista_valores.setObjectName("lista_valores")
        self.horizontalLayout_6.addWidget(self.lista_valores)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(135, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.linha_peso = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.linha_peso.setFont(font)
        self.linha_peso.setObjectName("linha_peso")
        self.horizontalLayout.addWidget(self.linha_peso)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.adicionar_peso = QtWidgets.QPushButton(Form)
        self.adicionar_peso.setMinimumSize(QtCore.QSize(80, 40))
        self.adicionar_peso.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.adicionar_peso.setFont(font)
        self.adicionar_peso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.adicionar_peso.setObjectName("adicionar_peso")
        self.horizontalLayout_2.addWidget(self.adicionar_peso)
        self.excluir_peso = QtWidgets.QPushButton(Form)
        self.excluir_peso.setMinimumSize(QtCore.QSize(80, 40))
        self.excluir_peso.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.excluir_peso.setFont(font)
        self.excluir_peso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.excluir_peso.setObjectName("excluir_peso")
        self.horizontalLayout_2.addWidget(self.excluir_peso)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.linha_glicemia = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.linha_glicemia.setFont(font)
        self.linha_glicemia.setObjectName("linha_glicemia")
        self.horizontalLayout_3.addWidget(self.linha_glicemia)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.adicionar_glicemia = QtWidgets.QPushButton(Form)
        self.adicionar_glicemia.setMinimumSize(QtCore.QSize(80, 40))
        self.adicionar_glicemia.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.adicionar_glicemia.setFont(font)
        self.adicionar_glicemia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.adicionar_glicemia.setObjectName("adicionar_glicemia")
        self.horizontalLayout_5.addWidget(self.adicionar_glicemia)
        self.excluir_glicemia = QtWidgets.QPushButton(Form)
        self.excluir_glicemia.setMinimumSize(QtCore.QSize(80, 40))
        self.excluir_glicemia.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.excluir_glicemia.setFont(font)
        self.excluir_glicemia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.excluir_glicemia.setObjectName("excluir_glicemia")
        self.horizontalLayout_5.addWidget(self.excluir_glicemia)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.adicionar_banco_dados = QtWidgets.QPushButton(Form)
        self.adicionar_banco_dados.setMinimumSize(QtCore.QSize(120, 60))
        self.adicionar_banco_dados.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.adicionar_banco_dados.setFont(font)
        self.adicionar_banco_dados.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.adicionar_banco_dados.setObjectName("adicionar_banco_dados")
        self.verticalLayout_4.addWidget(self.adicionar_banco_dados, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Alimentar Banco de dados Glicemia"))
        self.ajuda.setText(_translate("Form", "?"))
        self.label_4.setText(_translate("Form", "Dia:"))
        self.label_5.setText(_translate("Form", "Mês:"))
        self.label_6.setText(_translate("Form", "Ano:"))
        self.label_2.setText(_translate("Form", "Peso:"))
        self.adicionar_peso.setText(_translate("Form", "A d i c i o n a r"))
        self.excluir_peso.setText(_translate("Form", "E x c l u i r"))
        self.label_3.setText(_translate("Form", "Valor da glicemia:"))
        self.adicionar_glicemia.setText(_translate("Form", "A d i c i o n a r"))
        self.excluir_glicemia.setText(_translate("Form", "E x c l u i r"))
        self.adicionar_banco_dados.setText(_translate("Form", "A d i c i o n a r"))
