# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tela_ajuda.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(491, 550)
        Form.setMinimumSize(QtCore.QSize(491, 550))
        Form.setMaximumSize(QtCore.QSize(491, 550))
        font = QtGui.QFont()
        font.setPointSize(20)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Bem vindo ao PreMia!"))
        self.label_2.setText(_translate("Form", "O PreMia é um software desenvolvido com o\n"
"intuito de fornecer dados estatísticos\n"
"para os valores de glicemia e pressão\n"
"e com isso, auxiliar na escolha do melhor\n"
"tratamento para o paciente."))
        self.label_3.setText(_translate("Form", "\n"
"No botão \"Acessar\", você será redirecionado à\n"
"janela de alimentação do banco de dados.\n"
"\n"
"O botão \"Criar\" levará você à janela de criação\n"
"do banco de dados. Verifique as informações\n"
"antes de criar o banco de dados,\n"
"uma vez criado é impossível excluí-lo.\n"
"\n"
"Clicando no botão \"Gráficos\", será aberta uma janela\n"
"para que possa escolher o banco de dados e o\n"
"tipo de gráfico a ser analisado.\n"
"Caso seja a primeira vez que o PreMia é aberto,\n"
"a visualização do gráfico\n"
"solicitado demorará alguns segundos."))
