# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tela_acessar_graficos_pressao.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        Form.setMinimumSize(QtCore.QSize(600, 400))
        Form.setMaximumSize(QtCore.QSize(600, 400))
        Form.setStyleSheet("QPushButton#abrir_pressao, #abrir_bpm{\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 10px\n"
"}\n"
"QPushButton#abrir_pressao:hover, #abrir_bpm:hover{\n"
"background-color: rgba(145, 207, 230, 200)\n"
"}\n"
"QPushButton#abrir_pressao:pressed, #abrir_bpm:pressed{\n"
"background-color: rgba(150, 150, 150, 255);\n"
"padding-top: 2px;\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.ajuda = QtWidgets.QPushButton(Form)
        self.ajuda.setMinimumSize(QtCore.QSize(30, 30))
        self.ajuda.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ajuda.setFont(font)
        self.ajuda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ajuda.setStyleSheet("QPushButton#ajuda{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 10px\n"
"}\n"
"QPushButton#ajuda:hover{\n"
"background-color: rgba(145, 207, 230, 200)\n"
"}\n"
"QPushButton#ajuda:pressed{\n"
"padding-top: 2px\n"
"}\n"
"")
        self.ajuda.setObjectName("ajuda")
        self.horizontalLayout_2.addWidget(self.ajuda)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(11, 27, 264, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(28, 5, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.media_pressao = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.media_pressao.setFont(font)
        self.media_pressao.setObjectName("media_pressao")
        self.verticalLayout.addWidget(self.media_pressao)
        self.desvio_padrao_pressao = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.desvio_padrao_pressao.setFont(font)
        self.desvio_padrao_pressao.setObjectName("desvio_padrao_pressao")
        self.verticalLayout.addWidget(self.desvio_padrao_pressao)
        self.variabilidade_pressao = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.variabilidade_pressao.setFont(font)
        self.variabilidade_pressao.setObjectName("variabilidade_pressao")
        self.verticalLayout.addWidget(self.variabilidade_pressao)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 271, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(50, 5, 5, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.media_bpm = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.media_bpm.setFont(font)
        self.media_bpm.setObjectName("media_bpm")
        self.verticalLayout_2.addWidget(self.media_bpm)
        self.desvio_padrao_bpm = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.desvio_padrao_bpm.setFont(font)
        self.desvio_padrao_bpm.setObjectName("desvio_padrao_bpm")
        self.verticalLayout_2.addWidget(self.desvio_padrao_bpm)
        self.variabilidade_bpm = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.variabilidade_bpm.setFont(font)
        self.variabilidade_bpm.setObjectName("variabilidade_bpm")
        self.verticalLayout_2.addWidget(self.variabilidade_bpm)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.abrir_pressao = QtWidgets.QPushButton(Form)
        self.abrir_pressao.setMinimumSize(QtCore.QSize(120, 40))
        self.abrir_pressao.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.abrir_pressao.setFont(font)
        self.abrir_pressao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.abrir_pressao.setObjectName("abrir_pressao")
        self.horizontalLayout_3.addWidget(self.abrir_pressao)
        spacerItem = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.abrir_bpm = QtWidgets.QPushButton(Form)
        self.abrir_bpm.setMinimumSize(QtCore.QSize(120, 40))
        self.abrir_bpm.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.abrir_bpm.setFont(font)
        self.abrir_bpm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.abrir_bpm.setObjectName("abrir_bpm")
        self.horizontalLayout_3.addWidget(self.abrir_bpm)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Gráficos Pressão"))
        self.ajuda.setText(_translate("Form", "?"))
        self.groupBox.setTitle(_translate("Form", "Gráficos Pressão"))
        self.media_pressao.setText(_translate("Form", "Média Pressão"))
        self.desvio_padrao_pressao.setText(_translate("Form", "Desvio Padrão Pressão"))
        self.variabilidade_pressao.setText(_translate("Form", "Variabilidade Pressão"))
        self.groupBox_2.setTitle(_translate("Form", "Gráficos BPM"))
        self.media_bpm.setText(_translate("Form", "Média BPM"))
        self.desvio_padrao_bpm.setText(_translate("Form", "Desvio Padrão BPM"))
        self.variabilidade_bpm.setText(_translate("Form", "Variabilidade BPM"))
        self.abrir_pressao.setText(_translate("Form", "A b r i r"))
        self.abrir_bpm.setText(_translate("Form", "A b r i r"))
