# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tela_acessar_graficos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        Form.setStyleSheet("QPushButton#acessar{\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 10px\n"
"}\n"
"QPushButton#acessar:hover{\n"
"background-color: rgba(145, 207, 230, 200)\n"
"}\n"
"QPushButton#acessar:pressed{\n"
"background-color: rgba(150, 150, 150, 255);\n"
"padding-top: 2px;\n"
"}\n"
"\n"
"QLineEdit#linha_nome{\n"
"border-radius: 10px;\n"
"}\n"
"QLineEdit#linha_nome:hover{\n"
"background-color: rgba(147, 207, 230, 100)\n"
"}\n"
"\n"
"QComboBox#combo_dia, #combo_mes, #combo_ano, #combo_mes_bd, #combo_ano_bd{\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 10px\n"
"}\n"
"QComboBox#combo_dia:hover, #combo_mes:hover, #combo_ano:hover, #combo_mes_bd:hover, #combo_ano_bd:hover{\n"
"background-color: rgba(147, 207, 230, 200)\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.ajuda = QtWidgets.QPushButton(Form)
        self.ajuda.setMinimumSize(QtCore.QSize(30, 30))
        self.ajuda.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ajuda.setFont(font)
        self.ajuda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ajuda.setStyleSheet("QPushButton#ajuda{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 10px\n"
"}\n"
"QPushButton#ajuda:hover{\n"
"background-color: rgba(145, 207, 230, 200)\n"
"}\n"
"QPushButton#ajuda:pressed{\n"
"padding-top: 2px\n"
"}\n"
"")
        self.ajuda.setObjectName("ajuda")
        self.horizontalLayout_3.addWidget(self.ajuda)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.linha_nome = QtWidgets.QLineEdit(Form)
        self.linha_nome.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.linha_nome.setFont(font)
        self.linha_nome.setStyleSheet("")
        self.linha_nome.setObjectName("linha_nome")
        self.horizontalLayout.addWidget(self.linha_nome)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, -1, 5, -1)
        self.formLayout.setHorizontalSpacing(25)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.combo_dia = QtWidgets.QComboBox(Form)
        self.combo_dia.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_dia.setFont(font)
        self.combo_dia.setObjectName("combo_dia")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_dia)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.combo_mes = QtWidgets.QComboBox(Form)
        self.combo_mes.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_mes.setFont(font)
        self.combo_mes.setObjectName("combo_mes")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_mes)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.combo_ano = QtWidgets.QComboBox(Form)
        self.combo_ano.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_ano.setFont(font)
        self.combo_ano.setObjectName("combo_ano")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.combo_ano)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, -1, 5, 0)
        self.gridLayout.setHorizontalSpacing(37)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.combo_mes_bd = QtWidgets.QComboBox(self.groupBox)
        self.combo_mes_bd.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_mes_bd.setFont(font)
        self.combo_mes_bd.setObjectName("combo_mes_bd")
        self.gridLayout.addWidget(self.combo_mes_bd, 1, 1, 1, 1)
        self.combo_ano_bd = QtWidgets.QComboBox(self.groupBox)
        self.combo_ano_bd.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_ano_bd.setFont(font)
        self.combo_ano_bd.setObjectName("combo_ano_bd")
        self.gridLayout.addWidget(self.combo_ano_bd, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, -1, 0, -1)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.glicemia = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.glicemia.setFont(font)
        self.glicemia.setObjectName("glicemia")
        self.verticalLayout.addWidget(self.glicemia)
        self.pressao = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pressao.setFont(font)
        self.pressao.setObjectName("pressao")
        self.verticalLayout.addWidget(self.pressao)
        self.glicemia_pressao = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.glicemia_pressao.setFont(font)
        self.glicemia_pressao.setObjectName("glicemia_pressao")
        self.verticalLayout.addWidget(self.glicemia_pressao)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.acessar = QtWidgets.QPushButton(Form)
        self.acessar.setMinimumSize(QtCore.QSize(120, 40))
        self.acessar.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.acessar.setFont(font)
        self.acessar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.acessar.setObjectName("acessar")
        self.verticalLayout_2.addWidget(self.acessar, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Acessar os Gráficos"))
        self.ajuda.setText(_translate("Form", "?"))
        self.label.setText(_translate("Form", "Nome:"))
        self.label_2.setText(_translate("Form", "Dia:"))
        self.label_3.setText(_translate("Form", "Mês:"))
        self.label_4.setText(_translate("Form", "Ano:"))
        self.groupBox.setTitle(_translate("Form", "Banco de dados"))
        self.label_5.setText(_translate("Form", "Mês:"))
        self.label_6.setText(_translate("Form", "Ano:"))
        self.glicemia.setText(_translate("Form", "Glicemia"))
        self.pressao.setText(_translate("Form", "Pressão"))
        self.glicemia_pressao.setText(_translate("Form", "Glicemia + Pressão"))
        self.acessar.setText(_translate("Form", "A c e s s a r"))
